### ISSUE TITLE
Allow Apps on top of DUBBD to not be from IronBank

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#157]
When running DUBBD as a runtime environment, there are often applications that need to get deployed that are not from IronBank.  

# Kvyerno Policies

There are current Kyverno policies in place that prevent, by default, installing Deployments, Statefulsets, Job and Pods that come from non-iron bank registries.  

# Options:

## Platform Registry Exception

Create a variable in DUBBD that lets platform admins set any registry that teams can pull from to allow zarf packages with particular registries to be allowed to be installed.

Pros:
* flexible in allowing zarf/non-zarf deployments

Cons:
* requires platform configuration
* Requires improvements to Zarf to allow a variable with a list of strings to be rendered.

## Only monitor Pods

* Let the deployments/Statefulsets/Jobs be free to configure any registry
* Restrict Pods to only be allowed to pull from 127.0.0.1 so they must be installed via Zarf and what's allowed/not is controlled externally

Pros:
* Allows anything to be installed, as long as it was installed with a zarf package

Cons:
* Requires updating the KyvernoPolicies.
* approvals and assurances of the "right"/"safe" things being installed via zarf are removed.  This would require a more robust solution (e.g. signing verification) to provide better checks would be needed.

**Comment by zachariahmiller** [comment]
+1 to platform registry exception option.

**Comment by ntwkninja** [comment]
I think [this](https://repo1.dso.mil/big-bang/product/packages/kyverno-policies/-/blob/main/chart/values.yaml?ref_type=heads#L204-223) is much more valuable than which registry you pull from (cryptographic validation of artifacts on admission based upon a provided list of trusted signatories). 

https://kyverno.io/docs/writing-policies/verify-images/

**Comment by mjnagel** [comment]
> I think [this](https://repo1.dso.mil/big-bang/product/packages/kyverno-policies/-/blob/main/chart/values.yaml?ref_type=heads#L204-223) is much more valuable than which registry you pull from (cryptographic validation of artifacts on admission based upon a provided list of trusted signatories).
> 
> https://kyverno.io/docs/writing-policies/verify-images/

Would echo this - Big Bang has a policy in place for verifying image are signed from Ironbank (although it isn't enabled/enforced yet). I think it would be valuable to think through how DUBBD/Zarf would handle this policy.

**Comment by zachariahmiller** [comment]
@mjnagel The enforcement of the registry source exists today though. Additionally, kyverno states in the doc you linked that the feature is "not ready for production". We are now speaking to the "more robust solution (e.g. signing verification) to provide better checks would be needed." @runyontr alluded to in option two above. 

My question would be:
BB's policy will likely still be restricting not just based on the key, but also a base repo URI correct?

If that is the case there are a couple of things I think we need to address:
- Does DUBBD need to support registry exception in the interim until this feature is accepted as ready for production?
- For implementing this feature in DUBBD, what level of granularity needs to be added to writing the policies and what does this look like? Since there is a desire to keep complexity to a minimum, do we think this would look like a list of registry/public keys that gets templated into the policy?
- What is the expectation around consumers already having a signing workflow in-place for their apps and related images? To that end is that a solution that might be developed separately as a capability offered by UDS?

**Comment by ntwkninja** [comment]
re: more robust solution, since the zarf agent is typically the first on the scene, I think it would make sense to have this type of mechanism baked in there

Also, since zarf is already handling the registry when the cluster is init'd, could we set that location as the approved registry source dynamically by passing variables between components?

**Comment by runyontr** [comment]
> To the original question in this issue...I might be missing something on "Requires updating the KyvernoPolicies.
" for option 2 (zarf registry as only allowed registry). Wouldn't this actually be easier than option 1 for config? No dynamic registry values required, just a "hardcoded" zarf registry as the only allowed registry in values?

The default clusterpolicy currently has this segment in it (i've added some things in it) that applies to deployments, SS, Jobs and DaemonSets.  We'd have to not restrict those

```
  - exclude:
      any:
      - resources:
          namespaces:
          - zarf
      - resources:
          namespaces:
          - metallb-system
      resources: {}
    match:
      all:
      - resources:
          kinds:
          - DaemonSet
          - Deployment
          - Job
          - StatefulSet
      resources: {}
    name: autogen-validate-registries
    preconditions:
      all:
      - key: '{{request.operation || ''BACKGROUND''}}'
        operator: In
        value:
        - CREATE
        - UPDATE
        - BACKGROUND
    validate:
      foreach:
      - list: request.object.spec.template.spec.[ephemeralContainers, initContainers,
          containers][]
        pattern:
          image: registry1.dso.mil* | registry.dso.mil* | registry1.dso.mil* | registry.dso.mil*
            | 127.0.0.1*
      message: Image registry is not in the approved list
```
