### ISSUE TITLE
Make the DUBBD+AWS distro OCI skeleton friendly

### ISSUE THREAD

**Issue by kirankt** [defenseunicorns/uds-package-dubbd#222]
Hello,
I'm trying to use the dubbd-aws OCI skeleton package and I'm running into issues while creating and deploying the imported package. 

The intent of creating this issue is to track the creation/publishing of the DUBBD+AWS OCI skeleton image and documenting its potential use.

I've published an OCI skeleton with the following set of commands:
```
git clone https://github.com/defenseunicorns/zarf-package-big-bang
cd zarf-package-big-bang/aws
zarf package publish . oci://ghcr.io/kirankt/packages
```

Using https://github.com/defenseunicorns/delivery-mvp-dubbd/blob/bb-oci-import/zarf.yaml, `zarf package create` fails with the following error:
```
                                                                                                      
  📦 LOKI-MODULE COMPONENT                                                                            
                                                                                                      

     ERROR:  Failed to publish package: unable to copy file loki/.terraform: lstat loki/.terraform: no such file
             or directory

```
This is due to the fact that there is no 'onCreate' action in a package skeleton. It expects the assets to already exist before creation/publishing.  Making a minor modification leads to better results during creation.

```
  - name: loki-module
    required: true
      - source: loki/main.tf
        target: run/loki/main.tf
      - source: loki/variables.tf
        target: run/loki/variables.tf
      - source: loki/output.tf
        target: run/loki/output.tf
      - source: loki/terraform.tfvars
        target: run/loki/terraform.tfvars
  - name: execute-terraform
    required: true
    actions:
      onDeploy:
        before:
          - cmd: test -d ./loki/ && chmod -R ugo+rwx ./loki/ || echo $?
            dir: run
          - cmd: terraform get -update
            dir: run/loki
            ...
```
