### ISSUE TITLE
Conditionally Remove KMS and S3 bucket

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#244]
As a delivery engineer
When I remove the DUBBD-AWS package
I want the Loki S3 bucket and  KMS key to be destroyed only if force destroys are set to "true"
So that on longer-lived clusters, removing DUBBD-AWS doesn't impact S3 and KMS

**Comment by justin-o12** [comment]
I thought we could use [Terraform's lifecycle](https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle), but I got an error talking about that being reserved for a future use.  I think it's because that isn't compatible with the module we're using at this time.

I spoke with Palassis and Zach, and we agreed that what could work in Rex's use case is a situation where he wants to remove DUBBD but not touch Terraform.  So, I am looking for a way to not perform a `terraform destroy` if the `loki_force_delete` variable is `false`.

There was also talk about generalizing the variable from `loki_force_delete` to something like `ephemeral` to future-proof it.  

I am committing my effort to the `fix-key-arn` branch (at the time, I thought the problem was the ARN, but that's not the case).  The shell script in the `cmd` of the `zarf.yaml` is complaining about:
```
     sh: 1: [: =: unexpected operator
  ✔  Completed "if [ $ZARF_VAR_LOKI_FORCE_DESTROY = "true" ]; then terraf..."
```
After running:
```
zarf p create --confirm && zarf p deploy --confirm ./zarf-package-big-bang-distro-aws-amd64-0.2.1.tar.zst --set name=jno-bigbang-aws-install --set loki_force_destroy=true ; zarf p remove --confirm ./zarf-package-big-bang-distro-aws-amd64-0.2.1.tar.zst --components execute-terraform
```

**Comment by MxNxPx** [comment]
@justin-o12 - I would like to confirm with someone, but i don't know if the deploy var will be available to zarf on destroy like we thought.  new hair-brained idea, what we if create a configmap on deploy and read in from it on destroy...
```yaml
components:
  - name: execute-terraform
    required: true
    actions:
      onDeploy:
        before:
          - cmd: ./zarf tools kubectl create cm -n zarf zarf zarf-bigbang-tf-destroy --from-literal=ephemeral=${ZARF_VAR_EPHEMERAL} -oyaml --dry-run=client | ./zarf tools kubectl apply -f -;
      onRemove:
        before:
          - cmd: |
              TERRAFORM_DESTROY=$(./zarf tools kubectl get cm -n zarf zarf-bigbang-tf-destroy -ojsonpath='{.data.ephemeral}')
              echo "${TERRAFORM_DESTROY}" | grep "true" && echo "terraform destroy with LOKI_FORCE_DESTROY=${TERRAFORM_DESTROY}" || echo "do nothing";
```
