### ISSUE TITLE
Create e2e test for the repo

### ISSUE THREAD

**Issue by kirankt** [defenseunicorns/uds-package-dubbd#3]
We need to automate e2e test jobs when new changes are pushed to the repo.

**Comment by runyontr** [comment]
Was thinking about how to do this, and think we could use Zarf Imports to build and deploy the package we want and then add our custom tests afterwards:

```yaml

components:
- name: cocowow
  required: true
  import:
    path: ../defense-unicorns-distro
    name: bigbang
- name: test
   files:
   - source: test-script.sh
     destination: test-script.sh
   actions:
   - cmd: ./zarf do some stuff
   - cmd: ./test-scrip.sh that also checks things
```
