### ISSUE TITLE
Configure default storage class

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#348]
As a DUBBD user
If a PersistentVolume gets deleted
I don't want the underlying EBS volume to get deleted
So that I am less likely to lose data

**Comment by mjnagel** [comment]
Is this targeted for "DUBBD-AWS" or "UDS Core-AWS"? I lean towards the latter - if you are bringing your own cluster (DUBBD-AWS) then you likely would bring your own default storage class too?

I assume we want this as a zarf var, maybe tied to existing loki deletion as well (switch to generic `ephemeral` var)?

**Comment by UncleGedd** [comment]
Good question, I was actually thinking this would target both packages, but there may be more to this ticket than I originally thought. Do you think we should discuss what type of StorageClass we could be opinionated on?

**Comment by mjnagel** [comment]
Yeah I think it's worth discussing. My initial 2cents would be that we setup something like this:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
reclaimPolicy: ###ZARF_VAR_SOMETHING###
```

Opinions we would have here:
- our storage class should be the default - self explanatory and makes sure that we don't have to deal with configuring all the DUBBD things to use it.
- volume expansion should be allowed - I think this is best especially while we are relying on PVCs for grafana, prometheus, etc, which the end user might want to resize eventually.
- volumes shouldn't be bound until used - feels better to be slower than to over-provision volumes that might not be used?
- ebs over efs - efs is far more expensive and I don't think we have a use case for this yet - might be worth exploring as an alternative (non-default) storage class in the future if the need arises.
- gp2 over gp3 - I don't have a strong opinion on this one...gp3 can be more cost effective and/or more performant in some scenarios but I lean towards gp2 as a more generic baseline?

User configurable options:
- reclaim policy - really this would just be for dev vs prod ideally, along the same lines as exposing the loki force delete of S3. I think the idea of a general `ephemeral` value has been floated around, which might control all of these knobs together.
