### ISSUE TITLE
Feature Request: Allow multiple domains/certificates

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/uds-package-dubbd#408]
As a user of uds-dubbd, I need to be able to provide 2 certificates/domains to the dubbd pkg deploy to separate my admin apps from my mission apps with different certificates for the sake of security. For example, I need to create private DNS for `admin.bigbang.dev` (admin apps) and `bigbang.dev` (mission apps). This will include separate certs for each domain and those certs associated to the different gateways (admin and tenant).

**Comment by brianrexrode** [comment]
After testing the `dubbd_values` feature I'm able to customize `hosts` entries for my deployment of the admin GW as well as the virtual services `hosts` entries for applications using the `admin` GW. The only outstanding issue I have is with having a completely different certificate for my `admin` domain (vs the `tenant` GW/domain)

I'm wondering if it would be feasible to add a `ZARF_VAR_PRIVATE_CERT` and `ZARF_VAR_PRIVATE_KEY` variables in order to specify an admin cert/key. 

Would it be possible to add `after:` commands to account for this newly proposed variables like (`defense-unicorns-distro/zarf.yaml` entry):
``` 
 - name: load-certs
    required: true
    files:
      - source: bigbang.dev.cert
        target: bigbang.dev.cert
      - source: bigbang.dev.key
        target: bigbang.dev.key
    actions:
      onDeploy:
        after:
          - cmd: "cat ${ZARF_VAR_CERT_FILE}"
            description: Read cert file into values
            mute: true
            setVariables:
              - name: PUBLIC_CERT
                sensitive: true
                autoIndent: true
          - cmd: "cat ${ZARF_VAR_KEY_FILE}"
            description: Read key file into values
            mute: true
            setVariables:
              - name: PUBLIC_KEY
                sensitive: true
                autoIndent: true
          - cmd: "cat ${ZARF_VAR_PRIVATE_CERT}"
            description: Read cert file into values
            mute: true
            setVariables:
              - name: PRIVATE_CERT
                sensitive: true
                autoIndent: true
          - cmd: "cat ${ZARF_VAR_PRIVATE_KEY}"
            description: Read key file into values
            mute: true
            setVariables:
              - name: PRIVATE_KEY
                sensitive: true
                autoIndent: true
          - cmd: rm bigbang.dev.cert
          - cmd: rm bigbang.dev.key
```
then update  `values/istio.yaml`  with:
```
    admin:
      ingressGateway: admin-ingressgateway
      hosts:
        - "*.{{ .Values.domain }}"
      tls:
        key: |
          ###ZARF_VAR_PRIVATE_KEY###
        cert: |
          ###ZARF_VAR_PRIVATE_CERT###
        minProtocolVersion: "TLSV1_3"
    public: null
```
users could then configure a `zarf-config.yaml` pointed to the corresponding public and private cert/key and if they don't have separate certs just reference the same cert/key for both sets of ZARF_VARs.
