### ISSUE TITLE
Velero CRD for cluster backups

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#51]
```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
spec:
  provider: aws
  objectStorage:
    bucket: your-bucket-name
    prefix: backups/
  config:
    region: your-aws-region
---
apiVersion: velero.io/v1
kind: BackupSchedule
metadata:
  name: all-namespaces-backup
spec:
  schedule: "0 0 * * *" # every day at midnight may or may not be good enough
  template:
    ttl: 720h
    includedNamespaces:
    - "*"
    snapshotVolumes: true # also backup PVCs
    storageLocation: default # save to the above location

```
