### ISSUE TITLE
Add S3 terraform and IRSA to Velero for AWS backups

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#52]
S3 bucket should be :
* encrypted
* versioned (backed up)

Something like this for the velero config:

```yaml
velero:
  configuration:
    provider_config:
      aws:
        s3ForcePathStyle: "true"
        region: "your-aws-region"
        s3Url: "https://your-s3-endpoint-url"
    backupStorageLocation:
      name: "your-backup-location-name"
      bucket: "your-bucket-name"
      config:
        region: "your-aws-region"
        s3ForcePathStyle: "true"
        s3Url: "https://your-s3-endpoint-url"
      accessMode: "ReadWrite"
    volumeSnapshotLocation:
      name: "your-snapshot-location-name"
      provider: "aws"
      config:
        region: "your-aws-region"
        s3ForcePathStyle: "true"
        s3Url: "https://your-s3-endpoint-url"
      deleteOtherSnapshots: true
  credentials:
    existingSecret: "your-aws-secret-name"
  backupStorageLocations:
    - name: "your-backup-location-name"
      provider: "aws"
      bucket: "your-bucket-name"
      config:
        region: "your-aws-region"
        s3ForcePathStyle: "true"
        s3Url: "https://your-s3-endpoint-url"
      accessMode: "ReadWrite"
  volumeSnapshotLocations:
    - name: "your-snapshot-location-name"
      provider: "aws"
      config:
        region: "your-aws-region"
        s3ForcePathStyle: "true"
        s3Url: "https://your-s3-endpoint-url"
      deleteOtherSnapshots: true
  rbac:
    create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "your-irsa-role-arn"
```
