### ISSUE TITLE
Research Apache v2 Licensed Object Storage Solutions

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#58]
Apache Ozone: https://ozone.apache.org/docs/1.3.0/

What License is Ceph?

# Ceph

## Object Storage

1. Ceph Cluster

<details>
  <summary> CephCluster </summary>
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph
spec:
  cephVersion:
    allowUnsupported: true
    image: quay.io/ceph/ceph:v17
  crashCollector:
    disable: true
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  mgr:
    allowMultiplePerNode: true
    count: 1
  mon:
    allowMultiplePerNode: true
    count: 3
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi  # how big the monitor PVCs are
        storageClassName: gp2
  priorityClassNames:
    all: system-node-critical
    mgr: system-cluster-critical
  security:
    keyRotation:
      enabled: false
  storage:
    onlyApplyOSDPlacement: false
    storageClassDeviceSets:
    - count: 3 # how many OSDs
      encrypted: false
      name: set1
      placement:
        topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      portable: true
      preparePlacement:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
            weight: 100
        topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd-prepare
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
      tuneDeviceClass: true
      tuneFastDeviceClass: false
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi # how big the data PVCs are
          storageClassName: gp2
          volumeMode: Block
```
</details>

3. Ceph Object Store (this doesn't reference the ceph cluster....?)

<details>
  <summary>CephObjectStore</summary>
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 1
```
</details>

4. Bucket Storage Class
> The storage class defines the object storage system, the bucket retention policy, and other properties required by the administrator. 

<details>
  <summary> StorageClass</summary>
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-bucket
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: my-store
  objectStoreNamespace: rook-ceph
```
</details>

5. Bucket

<details>
  <summary>ObjectBucket</summary>
```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket
spec:
  generateBucketName: ceph-bkt
  storageClassName: rook-ceph-bucket
```
</details>

## Access To Objects:

```console
export AWS_HOST=$(kubectl -n default get cm ceph-bucket -o jsonpath='{.data.BUCKET_HOST}')
export PORT=$(kubectl -n default get cm ceph-bucket -o jsonpath='{.data.BUCKET_PORT}')
export BUCKET_NAME=$(kubectl -n default get cm ceph-bucket -o jsonpath='{.data.BUCKET_NAME}')
export AWS_ACCESS_KEY_ID=$(kubectl -n default get secret ceph-bucket -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 --decode)
export AWS_SECRET_ACCESS_KEY=$(kubectl -n default get secret ceph-bucket -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 --decode)
alias s3="aws s3 --endpoint https://s3.tom.bigbang.dev"
```

```console
s3 cp ../../zarf-package-big-bang/defense-unicorns-distro/zarf-package-big-bang-amd64-1.57.0.tar.zst s3://${BUCKET_NAME}/ 
s3 ls s3://${BUCKET_NAME}
2023-04-13 07:44:08 2683912247 zarf-package-big-bang-amd64-1.57.0.tar.zst
```

## Deployment

Ceph can run both in EKS and On Prem.   OnPrem requires specific node setup to allow for partitioning for blocks.  EKS can leverage an existing StorageClass

### EKS:

Can use PVCs for the underlying data store

<details>
  <summary> Sample Ceph Cluster </summary>
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph
spec:
  cephVersion:
    allowUnsupported: true
    image: quay.io/ceph/ceph:v17
  crashCollector:
    disable: true
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  mgr:
    allowMultiplePerNode: true
    count: 1
  mon:
    allowMultiplePerNode: true
    count: 3
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp2
  priorityClassNames:
    all: system-node-critical
    mgr: system-cluster-critical
  security:
    keyRotation:
      enabled: false
  storage:
    onlyApplyOSDPlacement: false
    storageClassDeviceSets:
    - count: 3
      encrypted: false
      name: set1
      placement:
        topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      portable: true
      preparePlacement:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd
                - key: app
                  operator: In
                  values:
                  - rook-ceph-osd-prepare
              topologyKey: kubernetes.io/hostname
            weight: 100
        topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd-prepare
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
      tuneDeviceClass: true
      tuneFastDeviceClass: false
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: gp2
          volumeMode: Block
```
</details>

Integrations:

## Prometheus

https://docs.ceph.com/en/quincy/mgr/dashboard/#enabling-prometheus-alerting

### Manager UI

<details>
  <summary>Expose the Manager Dashboard</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-dashboard-external-http
  namespace: rook-ceph # namespace:cluster
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph # namespace:cluster
spec:
  ports:
    - name: dashboard
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: rook-ceph-mgr
  sessionAffinity: None
  type: NodePort
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  gateways:
  - istio-system/public
  hosts:
  - rook-ceph.tom.bigbang.dev
  http:
  - route:
    - destination:
        host: rook-ceph-mgr-dashboard-external-http.rook-ceph.svc.cluster.local
        port:
          number: 7000
```

</details>

### Expose the S3 endpoints

<details>
  <summary> S3 Virtual Service </summary>

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-store-s3
  namespace: rook-ceph
spec:
  gateways:
  - istio-system/public
  hosts:
  - s3.tom.bigbang.dev
  http:
  - route:
    - destination:
        host: rook-ceph-rgw-my-store.rook-ceph.svc.cluster.local
        port:
          number: 80
```

</details>
