### ISSUE TITLE
prevent flux from rolling back new resources

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/uds-package-dubbd#606]
as a platform engineer upgrading dubbd, i would prefer a failed upgrade to leave the deploy in the exact failed state so i could troubleshoot.  right now it cleans up "new" resources after an upgrade fails, which could be disabled with this config:

```yaml
flux:
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
    cleanupOnFail: false   #<--- add this
```
