### ISSUE TITLE
Changes to Helm values specified in `DUBBD_VALUES` variable are not working

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-package-dubbd#654]
Expected behavior:

1. Deploy DUBBD having having set some helm values using the `DUBBD_VALUES` variable

example:
```
istio:
  values:
    meshConfig:
      meshMTLS:
        # DUBBD by default forces TLSv1.3+, but Amazon Linux 2 can't do 1.3 without a bunch of extra work, so we're falling back to requiring TLSv1.2+. There has been no formal data for TLSv1.2 deprecation. Some suspect it will be in 2026.
        minProtocolVersion: TLSV1_2
  gateways:
    admin:
      tls:
        minProtocolVersion: TLSV1_2
    tenant:
      tls:
        minProtocolVersion: TLSV1_2
```

2. Update the values and redeploy

example that adds a label to the tenant-ingressgateway pods:
```
istio:
  values:
    meshConfig:
      meshMTLS:
        # DUBBD by default forces TLSv1.3+, but Amazon Linux 2 can't do 1.3 without a bunch of extra work, so we're falling back to requiring TLSv1.2+. There has been no formal data for TLSv1.2 deprecation. Some suspect it will be in 2026.
        minProtocolVersion: TLSV1_2
  gateways:
    admin:
      tls:
        minProtocolVersion: TLSV1_2
    tenant:
      tls:
        minProtocolVersion: TLSV1_2
  ingressGateways:
    tenant-ingressgateway:
      extraLabels:
        # This forces anything exposed via the tenant gateway to be protected behind keycloak, which is a lot more secure than having the app handle it.
        protect: keycloak
```

Expected outcome: The `istio-system/tenant-ingressgateway` pod is now labeled with the new `protect:keycloak` label

Actual outcome: No change. Neither the tenant-ingressgateway deployment nor the pod contains the new label. If I completely tear down and redeploy the label is there, but isn't there if it is a "update and redeploy"
