### ISSUE TITLE
Expose NetworkPolicy configurations

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#79]
When configuring to use NetworkPolicies, the controlPlane CIDR block, nodeCIDR block and vpcCIDR block are needed to ensure communication is not blocked unnecessarily

```yaml
networkPolicies:
  enabled: true
  controlPlaneCidr: "10.200.32.0/19"
  nodeCidr: "10.200.32.0/19"
  vpcCidr: "10.200.0.0/16"
```

These will eventually be provided by the IaC modules for EKS that are being build in defenseunicorns/iac and will need to be passed in.

What should default values be?
